import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        display: ["var(--font-inter)", "system-ui", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      colors: {
        violet: {
          50: "#fdf2f2",
          100: "#fce4e4",
          200: "#f8caca",
          300: "#f2a3a3",
          400: "#e86b6b",
          500: "#cc2b2b",
          600: "#b31f1f",
          700: "#8f1919",
          800: "#6b1313",
          900: "#4a0d0d",
          950: "#2b0707",
        },
        purple: {
          50: "#fdf2f2",
          100: "#fce4e4",
          200: "#f8caca",
          300: "#f2a3a3",
          400: "#e86b6b",
          500: "#cc2b2b",
          600: "#b31f1f",
          700: "#8f1919",
          800: "#6b1313",
          900: "#4a0d0d",
          950: "#2b0707",
        },
        indigo: {
          50: "#fdf2f2",
          100: "#fce4e4",
          200: "#f8caca",
          300: "#f2a3a3",
          400: "#e86b6b",
          500: "#cc2b2b",
          600: "#b31f1f",
          700: "#8f1919",
          800: "#6b1313",
          900: "#4a0d0d",
          950: "#2b0707",
        },
        "tbc-red": "#CC2B2B",
        "tbc-red-hover": "#B02424",
        "tbc-red-light": "#FDF2F2",
        "tbc-amber": "#F5A000",
        "tbc-amber-light": "#FFFBEB",
        "tbc-sidebar": "#111111",
        "tbc-sidebar-text": "#E5E5E5",
        "tbc-sidebar-active": "#CC2B2B",
        "tbc-sidebar-hover": "#1F1F1F",
        "tbc-sidebar-icon": "#888888",
        "surface-page": "#F3F4F6",
        "surface-card": "#ffffff",
        "surface-sidebar": "#111111",
        "surface-input": "#F9FAFB",
        "surface-hover": "#F3F4F6",
        "dark-page": "#0a0a0a",
        "dark-card": "#161616",
        "dark-sidebar": "#111111",
        "dark-input": "#0a0a0a",
        "dark-hover": "#1f1f1f",
        "accent-light": "#FDF2F2",
        "accent-dark": "#991f1f",
        "pending-bg": "#fef3c7",
        "pending-text": "#b45309",
        "pending-border": "#fde68a",
        "success-bg": "#f0fdf4",
        "success-text": "#15803d",
        "success-border": "#bbf7d0",
        "danger-bg": "#FDF2F2",
        "danger-text": "#CC2B2B",
        "danger-border": "#FCA5A5",
        "purple-bg": "#FDF2F2",
        "purple-text": "#CC2B2B",
        "purple-border": "#FECACA",
        navy: "var(--text-primary)",
        teal: "var(--tbc-red)",
        "sidebar-bg": "var(--tbc-sidebar)",
        "content-bg": "var(--bg-base)",
        "bg-base": "var(--bg-base)",
        "bg-surface": "var(--bg-surface)",
        "bg-surface-hover": "var(--bg-surface-hover)",
        "accent-violet": "var(--accent-violet)",
        "accent-teal": "var(--accent-teal)",
        "accent-pink": "var(--accent-pink)",
        "accent-amber": "var(--accent-amber)",
        "text-primary": "var(--text-primary)",
        "text-muted": "var(--text-muted)",
        "border-subtle": "var(--border-subtle)",
        "border-glow": "var(--border-glow)",
        border: "var(--border-subtle)",
        accent: "var(--accent-violet)",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "2xl": "1rem",
      },
      boxShadow: {
        card: "0 1px 2px rgba(0,0,0,0.05)",
        "card-hover": "0 4px 6px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.04)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
